export const JsPlaygroundComponentName = 'js-playground-component'
export const JsPlaygroundBlockName = 'js-playground-block'
export const PythonPlaygroundComponentName = 'python-playground-component'
export const PythonPlaygroundBlockName = 'python-playground-block'
export const TsPlaygroundComponentName = 'ts-playground-component'
export const TsPlaygroundBlockName = 'ts-playground-block'
